#!/bin/bash

# take a component and a directory as arguments, write to stdout a 
# MANIFEST file fragment
if [ -z "${RPM}" ]; then
  RPM=/bin/rpm
fi

component=$1
dir=$2

srpms=$(/bin/ls -1 ${dir}/*.src.rpm 2>/dev/null)

if [ -z "${srpms}" ]; then
  echo "No SRPMS available. Unable to create MANIFESTs." >/dev/stderr
  exit
fi

for path in ${srpms}; do
  name=$(${RPM} --qf "%{name}" -qp ${path})
  license=$(${RPM} --qf "%{License}" -qp ${path})
  license=$(echo ${license} | /bin/sed -e 's/\s/_/g')
  echo "${component} ${license} file ${path}"
done
